version: '3.8'

services:
  web-service:
    build:
      context: ./web-service/web-service
      dockerfile: Dockerfile
    container_name: web-service
    ports:
      - "8081:8080"
    networks:
      - app-network
    depends_on:
      - db
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/userDb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Abhilasha@123
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    volumes:
      - ./target/web-service-0.0.1-SNAPSHOT.jar:/app/web-service-0.0.1-SNAPSHOT.jar

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: Abhilasha@123
      MYSQL_DATABASE: userDb
    ports:
      - "3307:3307"
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6380:6379"  # Map the host's 6380 to container's 6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
    driver: local
